# Generated by Django 4.2.2 on 2023-06-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_remove_product_discount_remove_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_state',
        ),
    ]
