# Generated by Django 4.2.2 on 2023-06-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0004_remove_checkout_tracking_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='checkout',
            name='tracking_number',
            field=models.CharField(default=223, max_length=100),
            preserve_default=False,
        ),
    ]
